### ISSUE TITLE
Matcher Class documentation page is not being rendered correctly

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetApiDocs#42]
[Matcher Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=aspnetcore-2.0) documentation page is not being rendered correctly.

I've looked at the [source](https://github.com/aspnet/ApiDocs/blob/live/api/xml/Microsoft.Extensions.FileSystemGlobbing/Matcher.xml) and couldn't anything wrong with it.

/cc @BillWagner @mairaw

**Comment by mairaw** [comment]
Tagging @Rick-Anderson and @scottaddie to follow up on this one.

**Comment by Rick-Anderson** [comment]
I though @dend  handles API problems?

**Comment by Rick-Anderson** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.FileProviders.Physical/ 
@natemcmaster is that correct?

**Comment by natemcmaster** [comment]
This API comes from the Microsoft.Extensions.FileSystemGlobbing package. https://github.com/aspnet/FileSystem/tree/2.1.0/src/FS.Globbing

**Comment by joelmartinez** [comment]
@dend yeah possibly ... depends on how the [ecma2yaml xsl transformation](https://github.com/docascode/ECMA2Yaml/blob/60a5f0f2a53ae25649bbc7fbf1090f81700f72f0/ECMA2Yaml/ECMAHelper/Transform/ECMADocsTransform.xsl#L142) translates these nested bullet lists from a formatting perspective ... it _looks_ like it should be outputting an HTML block, which I'd think wouldn't be subject to markdown's indent-based formatting. @TianqiZhang, do you know if there's any further transformations from that HTML into markdown, or otherwise how these nested lists will be transformed after Ecma2Yaml's output?

**Comment by Rick-Anderson** [comment]
@TianqiZhang, do you know if there's any further transformations from that HTML into markdown, or otherwise how these nested lists will be transformed after Ecma2Yaml's output?

**Comment by dend** [comment]
Ping @TianqiZhang
