### ISSUE TITLE
How to save configurations!

### ISSUE THREAD

**Issue by moyanming** [dotnet/AspNetApiDocs#89]
I can [set a value of the key](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationroot.item?view=aspnetcore-2.1#Microsoft_Extensions_Configuration_ConfigurationRoot_Item_System_String_), but how to save this value to the file (e.g. ini file)?
`var config = ConfigurationBuilder().AddIniFIle("c:\test.ini").Build();
config["test"] = "ok";`

**Comment by bitbonk** [comment]
The `Microsoft.Extension.Configuration.*` nuget packages do not provide means to save configuration. Please see https://github.com/aspnet/Configuration/issues/385 for more details.

**Comment by XelaNimed** [comment]
In my opinion a redesign is needed. This behavior made sense when using ASP, but not now. Now it is assumed that the library can be used in native applications (WinForms, WPF, Console), but the lack of the ability to save the settings makes it practically useless.

**Comment by Taschenbuch** [comment]
before: type safe and super easy way to save/persist and load settings to applocal data. It was just awesome.
now: quite useless.

**Comment by shaggygi** [comment]
Yup, I was just trying to use this in an API (outside of ASP.NET Core app) and need the ability to save updates.  This is a needed feature.

**Comment by andrewpros** [comment]
Is there any progress on this? .Net Core is now not only used with asp.net, its just silly we don't have a simple save ability without any reason provided, its even more funny that it is internally using System.Text.Json already for AddJsonFile to load it, a simple one-liner like File.WriteAllText(dir, JsonSerializer.Serialize(appSettings)) is enough to save it, but they still insist to not add writing ability to the whole configuration system, it would have so much more sense to support this with any config files.

**Comment by TygreWolf** [comment]
I'll also ask if there's been any progress on this.  I'm in the middle of updating a WPF application to .NET core, using a host builder and configuring with appsettings.json.  I love the ability to DI the configuration directly into objects I can load with IOptions, but without the ability to save setting modifications made by users of the application back to the JSON file, the functionality for non-ASP.NET applications is simply incomplete.

**Comment by Rick-Anderson** [comment]
Closing because this is not an API doc issue.

**Comment by dombrovsky** [comment]
> I'll also ask if there's been any progress on this. I'm in the middle of updating a WPF application to .NET core, using a host builder and configuring with appsettings.json. I love the ability to DI the configuration directly into objects I can load with IOptions, but without the ability to save setting modifications made by users of the application back to the JSON file, the functionality for non-ASP.NET applications is simply incomplete.

I was facing similar need in WPF project and it boiled down for me into two separate problems to solve:
1. Make IConfiguration indexer setter write back into persisted configuration source.
2. Be able to use types used with IOptions to modify configuration in a type-safe way.

Since in my case the application had to store configuration in Windows Registry, for addressing first problem we implemented custom [IConfigurationProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationprovider?view=dotnet-plat-ext-7.0) that would write back to Windows Registry on [Set()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationprovider.set?view=dotnet-plat-ext-7.0#microsoft-extensions-configuration-iconfigurationprovider-set(system-string-system-string)).
For addressing 2nd point ended up with [this](https://github.com/dombrovsky/MutableOptions).
